import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service - Undervolt",
  description: "Terms of service for Undervolt energy infrastructure platform",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white pt-20 pb-16">
      <div className="max-w-3xl mx-auto px-6">
        <Link href="/" className="inline-flex items-center gap-2 text-white/50 hover:text-white mb-8 text-sm">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
        
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/50 mb-8">Last updated: February 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">Acceptance of Terms</h2>
            <p className="text-white/70">
              By accessing and using Undervolt, you agree to these Terms of Service. If you do not agree, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Description of Service</h2>
            <p className="text-white/70">
              Undervolt is a platform that analyzes public construction permit data from Austin, Texas
              to provide insights about energy infrastructure. The service includes data visualization, AI-powered queries,
              and analytics dashboards.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">User Accounts</h2>
            <ul className="list-disc list-inside text-white/70 space-y-2">
              <li>You may use basic features without an account</li>
              <li>Custom AI queries require email registration</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must provide accurate information when registering</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Acceptable Use</h2>
            <p className="text-white/70">You agree NOT to:</p>
            <ul className="list-disc list-inside text-white/70 mt-2 space-y-1">
              <li>Abuse or overload our AI inference systems</li>
              <li>Attempt to bypass rate limits or access controls</li>
              <li>Use automated tools to scrape or access the service</li>
              <li>Reverse engineer or attempt to extract our AI models</li>
              <li>Use the service for any illegal purpose</li>
              <li>Impersonate others or provide false information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">AI Features & Limitations</h2>
            <ul className="list-disc list-inside text-white/70 space-y-2">
              <li>AI responses are generated by local and cloud-based language models</li>
              <li>Responses may contain errors or inaccuracies</li>
              <li>AI features are provided "as-is" without guarantees</li>
              <li>We may modify or discontinue AI features at any time</li>
              <li>Pre-built questions are available to all users; custom queries require sign-in and approval</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Data & Accuracy</h2>
            <p className="text-white/70">
              Our data is sourced from Austin Open Data Portal. While we strive for accuracy, we make no guarantees 
              about the completeness or correctness of the data or analysis. Do not rely on this service for 
              critical decisions without independent verification.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Intellectual Property</h2>
            <ul className="list-disc list-inside text-white/70 space-y-2">
              <li>The Undervolt name and logo are our trademarks</li>
              <li>Permit data is public domain from the City of Austin</li>
              <li>All other intellectual property rights are reserved</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Disclaimer of Warranties</h2>
            <p className="text-white/70">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, 
              INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
            <p className="text-white/70">
              IN NO EVENT SHALL UNDERVOLT OR ITS TEAM BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, 
              OR CONSEQUENTIAL DAMAGES ARISING OUT OF YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Changes to Terms</h2>
            <p className="text-white/70">
              We may update these terms at any time. Continued use of the service after changes 
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Contact</h2>
            <p className="text-white/70">
              Questions about these terms? Contact{" "}
              <a href="mailto:undervolt-team@aisoft.us" className="text-emerald-400 hover:underline">
                undervolt-team@aisoft.us
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
